sonar.organization=aharisov
sonar.projectKey=aharisov_oc_projet10_ci-cd
sonar.projectName=BobApp

sonar.sources=back/src/main,front/src/app
sonar.tests=back/src/test,front/src/app

sonar.java.binaries=back/target/classes

sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/*.spec.ts
sonar.test.inclusions=**/*.spec.ts,**/*Test.java,**/*Tests.java